nodes: 1
tasks_per_node: 1
tag: inat-16f
eval_name: video_sync_frozen
resume_checkpoint: false
data:
  root_path: /home/yosubs/koa_scratch/ntu/jepa/
  image_folder: frames/
  num_classes: 10000
  resolution: 224
  dataset_name: ntu
optimization:
  num_epochs: 1
  batch_size: 16
  weight_decay: 0.001
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
pretrain:
  model_name: vit_large
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 1
  tubelet_size: 2
  uniform_power: true
  use_sdpa: true
  use_silu: false
  tight_silu: false
  patch_size: 16
  folder: /home/yosubs/tmp/jepa/
  checkpoint: vitl16.pth.tar  # name of pretrained model file inside folder
  write_tag: jepa
